# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVbNY-2XKpj_3OiFfal18NBHc8CAwh7z
"""

x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())
if (x1, y1) == (x2, y2):
    print("No")
else:
    if 0 <= x2 < 8 and 0 <= y2 < 8 and checkerboard[x2][y2] == 0:
        if abs(x2 - x1) <= 1 and abs(y2 - y1) <= 1:
            print("Yes")
        else:
            print("No")
    else:
        print("No")